name: Sync preset.json from GitHub Issues

on:
  issues:
    types: [opened]

jobs:
  update-preset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get issue body
        id: get_body
        uses: actions/github-script@v6
        with:
          script: |
            return context.payload.issue.body

      - name: Extract JSON content from issue body
        id: extract_json
        run: |
          echo "Extracting JSON from issue body..."
          ISSUE_BODY='${{ steps.get_body.outputs.result }}'
          # 提取代码块中的 JSON 内容，去掉 ```json 和 ```
          JSON_DATA=$(echo "$ISSUE_BODY" | sed -n '/```json/,/```/p' | sed '1d;$d')
          echo "Extracted JSON data:"
          echo "$JSON_DATA"
          echo "$JSON_DATA" > src/preset_new.json

      - name: Validate JSON format
        run: |
          jq empty src/preset_new.json

      - name: Commit and push updated preset.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mv src/preset_new.json src/preset.json
          git add src/preset.json
          git commit -m "Update src/preset.json from issue #${{ github.event.issue.number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
